# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a14ab6032a37c7bc9f7e5f7a5fa20dc662ea05e9a7a9331426b264af71655e721a4c7fab1627613e1443532cbdb00ea864dfdeccebfc2efb6bfaa1dd0f2b9ba

test:
  secret_key_base: aaaddc8bce6d0cb8feaaf4f2cf7986b2e177a882b72c6bdee14cd349a6bcbb9a61cd4bb7c84325397b65d6cffb92fb49163d1e956c1537b18374cb4a8e2aa867

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
